pru/registers/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',


    url(
        regex=r'^miejscowosc-(?P<teryt_pk>\d+)/$',
        view=views.RegisterListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^$',
        view=views.RegisterListView.as_view(),
        name='list'
    ),

    url(
        regex=r'^~create/$',
        view=views.RegisterCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^^miejscowosc-(?P<teryt_pk>\d+)/~create$',
        view=views.RegisterCreateView.as_view(),
        name='create'
    ),

    url(
        regex=r'^~map/$',
        view=views.RegisterMapView.as_view(),
        name='map'
    ),

    url(
        regex=r'^api/list/$',
        view=views.register_api,
        name='list_api'
    ),
    url(
        regex=r'^api/list/-(?P<teryt_pk>\d+)/$',
        view=views.register_api,
        name='list_api'
    ),
    url(
        regex=r'^api/detail/(?P<pk>\d+)$',
        view=views.register_api,
        name='list_api'
    ),

    url(
        regex=r'^(?P<slug>[\w-]+)/$',
        view=views.RegisterDetailView.as_view(),
        name='detail'
    ),
)

pru/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',  # noqa
        TemplateView.as_view(template_name='pages/home.html'),
        name="home"),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^registers/', include('registers.urls', namespace="registers")),

    # Your stuff: custom urls go here

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pru/registers/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from autoslug import AutoSlugField
from django.utils.translation import ugettext_lazy as _
from teryt.models import JednostkaAdministracyjna
from model_utils import Choices
# TODO: Manager - public(), area()


class Community(JednostkaAdministracyjna):

    def get_absolute_url(self):
        url = reverse('registers:list', kwargs={'teryt_pk': self.pk})
        print url
        return url

    def get_absolute_api(self):
        return reverse('registers:list_api', kwargs={'teryt_pk': self.pk})

    class Meta:
        proxy = True


class RegisterQuerySet(models.QuerySet):
    # Available on both Manager and QuerySet.
    def public(self):
        return self.filter(public=True)

    def community(self, community, itself=True):
        return self.filter(community__in=community.get_descendants(itself))

    def for_user(self, user):
        if user.has_perm('registers.change_register'):
            return self
        return self.filter(public=True)

    def select_voivodeship(self):
        return self.select_related('community__parent__parent')


class Register(models.Model):
    STATUS = Choices((0, 'yes', _('yes')),
                     (1, 'no', _('no')),
                     (2, 'unknown', _('unknown')))
    slug = AutoSlugField(unique=True, populate_from='title')
    img = models.ImageField(null=True, blank=True, verbose_name=_("Featured image"))
    title = models.CharField(max_length=150, verbose_name=_("Institution name"))

    contractor = models.IntegerField(choices=STATUS, default=STATUS.unknown,
        verbose_name=_("Contractor data"), help_text=_('Name of each contractor'))
    id_data = models.IntegerField(choices=STATUS, default=STATUS.unknown,
        verbose_name=_("ID data of contractor"),
        help_text=_("Machine readable of contractor eg. KRS, REGON"))
    value = models.IntegerField(choices=STATUS, default=STATUS.unknown,
        verbose_name=_('Value of contract'),
        help_text=_('Value of each contract are published'))
    privacy = models.IntegerField(choices=STATUS, default=STATUS.unknown,
        verbose_name=_('Individual person name'),
        help_text=_('Name of contractor, even individual person'))
    text = models.IntegerField(choices=STATUS, default=STATUS.unknown,
        verbose_name=_('Text format'),
        help_text=_('Datasheet are published as text'))
    comparable = models.IntegerField(choices=STATUS, default=STATUS.unknown,
        verbose_name=_('Comparable'),
        help_text=_('Data are published in comparable form eg. spreadsheet, not PDF'))
    scan = models.IntegerField(choices=STATUS, default=STATUS.unknown,
        verbose_name=_('Scan'),
        help_text=_('Scan of most contract without enquire'))
    spending = models.IntegerField(choices=STATUS, default=STATUS.unknown,
        verbose_name=_('Information about spending'),
        help_text=_('Published data contains information about spneding without contracts too'))

    comment = models.TextField(verbose_name=_("Comment"), blank=True,
        help_text=_('Extra information about registers eg. story of publishing, heroes'))
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Reporter"),
        help_text=_('User who report contracts to us'))
    community = models.ForeignKey(Community, limit_choices_to={'level': 2},
        verbose_name=_('Community'))
    lat = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('Longtitude'))
    lng = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('Langtitude'))
    url = models.URLField(verbose_name=_("URL of publication"))
    public = models.BooleanField(default=False, verbose_name=_("Public"),
        help_text=_("Mark to publish on site"))
    created = models.DateTimeField(editable=False, verbose_name=_("Creation date"),
        auto_now_add=True)
    modified = models.DateTimeField(editable=False, verbose_name=_("Last modification date"),
        help_text=_("Date of last modification of this object"), auto_now=True)
    objects = RegisterQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse('registers:detail', kwargs={'slug': self.slug})

    def get_absolute_api(self):
        return reverse('registers:list_api', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.title

pru/registers/forms.py
from django.forms import ModelForm
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset
from braces.forms import UserKwargModelFormMixin
from .models import Register


class RegisterForm(UserKwargModelFormMixin, ModelForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        # self.helper.form_class = 'form form-horizontal'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('registers:create')
        self.helper.layout = Layout(
            Fieldset(
                _('Office data'),
                'title',
                'community',
                'img',
            ),
            Fieldset(
                _('Data about ingredients of registers'),
                'id_data',
                'value',
                'privacy',
                'text',
                'comparable',
                'scan',
                'spending',
                'comment',
                'url',
            ),
            Submit('submit', _('Submit')),
        )

    def save(self, commit=False, *args, **kwargs):
        obj = super(RegisterForm, self).save(commit=False, *args, **kwargs)
        print self.user
        obj.user = self.user
        obj.save()
        return obj

    class Meta:
        model = Register
        fields = ('img', 'title', 'id_data', 'value', 'privacy', 'text', 'comparable', 'scan',
            'spending', 'comment', 'community', 'url')

pru/registers/views.py
# from django.shortcuts import render
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import TemplateView
from braces.views import LoginRequiredMixin
from braces.views import UserFormKwargsMixin
from braces.views import FormValidMessageMixin
from braces.views import OrderableListMixin
from teryt.models import JednostkaAdministracyjna as Teryt
from .utils import paginator
from .utils import serializer_page
from .models import Register
from .forms import RegisterForm


ORDER_FIELD = {'title': 'title',
               'created': 'created',
               'voivodeship': 'community__parent__parent', }

API_FIELD = ('title', 'lat', 'lng', 'get_absolute_url', )


class PermissionMixin(object):

    def get_queryset(self, *args, **kwargs):
        qs = super(PermissionMixin, self).get_queryset(*args, **kwargs)
        return qs.for_user(self.request.user)


class RegisterCreateView(LoginRequiredMixin, UserFormKwargsMixin, FormValidMessageMixin,
         CreateView):
    model = Register
    form_class = RegisterForm

    def get_form_kwargs(self):
        kwargs = super(RegisterCreateView, self).get_form_kwargs()
        if 'teryt_pk' in self.kwargs:
            kwargs.update({'teryt': get_object_or_404(Teryt, pk=self.kwargs['teryt_pk'])})
        return kwargs

    def get_form_valid_message(self):
        return u"{0} created!".format(unicode(self.object))


class RegisterListView(PermissionMixin, OrderableListMixin, ListView):
    orderable_columns = ORDER_FIELD.values()
    orderable_columns_default = u"id"
    model = Register
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(RegisterListView, self).get_context_data(**kwargs)
        if hasattr(self, 'teryt'):
            context['teryt'] = self.teryt
            context['breadcrumbs'] = self.teryt.get_ancestors()
            context['children'] = self.teryt.get_children()
        else:
            context['children'] = Teryt.objects.filter(parent__isnull=True).all()
        return context

    def get_queryset(self, *args, **kwargs):
        qs = super(RegisterListView, self).get_queryset(*args, **kwargs)
        qs = qs.select_voivodeship()

        if 'teryt_pk' in self.kwargs:
            self.teryt = get_object_or_404(Teryt, pk=self.kwargs['teryt_pk'])
            qs = qs.community(self.teryt)
        return qs


class RegisterDetailView(PermissionMixin, DetailView):
    model = Register


class RegisterMapView(TemplateView):
    template_name = 'registers/register_map.html'


def register_api(request, pk=None, pk_teryt=None):
    object_list = Register.objects.public()

    if pk_teryt:
        object = get_object_or_404(Teryt, pk=pk)
        object_list = object_list.community(object)
    if pk:
        object_list = object_list.filter(pk=pk)
    paginated = paginator(request, object_list.all())
    results = serializer_page(paginated, API_FIELD)

    return JsonResponse(results, safe=False)

pru/registers/templates/registers/_order_link.html
{% if order_by != order_key or ordering != 'asc' %}
    [<a href="?order_by={{order_key}}">ASC</a>]
{% else %}
    [ASC]
{% endif %}

{% if order_by != order_key or ordering != 'desc' %}
    [<a href="?order_by={{order_key}}&ordering=desc">DESC</a>]
{% else %}
    [DESC]
{% endif %}

pru/registers/templates/registers/base.html
{% extends 'base.html' %}
{% block title %}Wykaz - {{block.super}}{% endblock %}
{%block content %}
{%block breadcrumb%}{%endblock%}
{%block main%}{%endblock%}
{%endblock%}

pru/registers/templates/registers/register_detail.html
{% extends 'registers/base.html' %}
{% load registers_tags staticfiles %}
{% block breadcrumb %}
<ol class="breadcrumb">
    <li><a href="{% url 'registers:list' %}">Index</a></li>
    {%for v in object.community.get_ancestors %}
        <li><a href="{%url 'registers:list' teryt_pk=v.pk%}">{{v}}</a></li>
    {%endfor%}
    <li><a href="{%url 'registers:list' teryt_pk=object.community.pk%}">{{object.community}}</a></li>
    <li class="active">{{object}}</li>

</ol>
{%endblock%}
{%block main%}
<a href="{% url 'registers:create' %}" class="btn btn-info">Report</a>
<a href="{% url 'registers:map' %}" class="btn btn-info">Map</a>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">{{object}}</h3>
  </div>
  {% if not object.public %}
    <div class="alert alert-info" role="alert">Object "{{object}}" is not public available</div>
  {% endif %}
  <div class="panel-body">
  {% if object.img %}<img src="{{object.img.url}}" title="{{object}}"> {% endif %}
  {{object.comment | safe}}
  </div>
  <table class="table">
  <tr><td>slug</td><td>{{object.slug}}</td></tr>
  <tr><td>img</td><td>{{object.img}}</td></tr>
  <tr><td>title</td><td>{{object.title}}</td></tr>
  <tr><td>id_data</td><td>{{object.id_data|display_register_status}}</td></tr>
  <tr><td>contractor</td><td>{{object.contractor|display_register_status}}</td></tr>
  <tr><td>privacy</td><td>{{object.privacy|display_register_status}}</td></tr>
  <tr><td>text</td><td>{{object.text|display_register_status}}</td></tr>
  <tr><td>comparable</td><td>{{object.comparable|display_register_status}}</td></tr>
  <tr><td>scan</td><td>{{object.scan|display_register_status}}</td></tr>
  <tr><td>spending</td><td>{{object.spending|display_register_status}}</td></tr>
  <tr><td>comment</td><td>{{object.comment}}</td></tr>
  <tr><td>user</td><td>{{object.user}}</td></tr>
  <tr><td>community</td><td>
    <a href="{{object.community.get_absolute_url}}">{{object.community}}</a>
  </td></tr>
  <tr><td>county</td><td>
    <a href="{{object.parent.get_absolute_url}}">{{object.community.parent}}</a>
  </td></tr>
  <tr><td>voivodeship</td><td>
    <a href="{{object.community.parent.parent.get_absolute_url}}">{{object.community.parent.parent}}</a>
  </td></tr>
  <tr><td>lat</td><td>{{object.lat}}</td></tr>
  <tr><td>lng</td><td>{{object.lng}}</td></tr>
  <tr><td>url</td><td>{{object.url}}</td></tr>
  <tr><td>public</td><td>{{object.public}}</td></tr>
  <tr><td>created</td><td>{{object.created}}</td></tr>
  <tr><td>modified</td><td>{{object.modified}}</td></tr>
  </table>
</div>
<div id="map-canvas"></div>
  <nav>
      <ul class="pager">
      {% if object.get_previous_by_created.public %}
          <li><a href="{{object.get_previous_by_created.get_absolute_url}}">{{object.get_previous_by_created}}</a></li>
      {% endif %}
      {% if object.get_next_by_created.public %}
          <li><a href="{{object.get_next_by_created.get_absolute_url}}">{{object.get_next_by_created}}</a></li>
      {% endif %}      </ul>
  </nav>
[<a href="{{object.get_absolute_api}}">API</a>]
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script src="{% static 'registers/map.js' %}"></script>
    <script type="text/javascript">
        init_map(document.getElementById("map-canvas"), "{{object.get_absolute_api}}")
    </script>
    {{block.super}}
{% endblock %}

pru/registers/templates/registers/register_form.html
{% extends 'registers/base.html' %}
{% load staticfiles crispy_forms_tags %}
{% block css %}
    {{block.super}}
    <style>
    #map-canvas {
        width: 100%;
        height: 500px;
    }
    </style>
    
{% endblock %}
{% block javascript %}
    {{block.super}}
    <script type="text/javascript" src='http://maps.google.com/maps/api/js?sensor=false&libraries=places'></script>
    <script src="{% static 'registers/locationpicker.jquery.js' %}"></script>
    <script type="text/javascript">
    /*$(function() {
        $('#map-canvas').locationpicker({
            radius: 0,
            enableAutocomplete: true,
            inputBinding: {
                latitudeInput: $('#id_lat'),
                longitudeInput: $('#id_lng'),
                locationNameInput: $('#id_title')
            },
        });
    });*/
    </script>
{% endblock %}
{% block main %}
{% crispy form %}
{% endblock%}

pru/registers/templates/registers/register_list.html
{% extends 'registers/base.html' %}
{#{% load pagination_tags %}#}
{% block breadcrumb %}
<ol class="breadcrumb">
    {% if teryt %}
    <li><a href="{% url 'registers:list'%}">Index</a></li>
    {% else %}
    <li class="active">Index</li>
    {% endif %}
    {%for v in breadcrumbs %}
        <li><a href="{% url 'registers:list' teryt_pk=v.pk%}">{{v}}</a></li>
    {%endfor%}

    {% if teryt %}
    <li class="active">{{teryt}}</li>
    {% endif %}

    {%if children %}
        <li>
        <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            Action <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
        {%for v in children %}
            <li><a href="{% url 'registers:list' teryt_pk=v.pk%}">{{v}}</a></li>
        {%endfor%}
        </ul>
        </div>
        </li>
    {%endif%}
</ol>
{% endblock %}
{% block main %}
<a href="{% url 'registers:create' %}" class="btn btn-info">Report</a>
<a href="{% url 'registers:map' %}" class="btn btn-info">Map</a>

{% load query_string %}
{%if object_list %}
    <table class="table">
        <thead>
        <tr>
            <th>Created{% include 'registers/_order_link.html' with order_key='created'%} </th>
            <th>Title {% include 'registers/_order_link.html' with order_key='title'%} </th>
            <th>Województwo{% include 'registers/_order_link.html' with order_key='community__parent__parent'%} </th>
        </tr>
        </thead>
        
        <tbody>
            {%for obj in object_list%}
            <tr>
                <td>{{ obj.created }}</td>
                <td><a href="{{obj.get_absolute_url}}">{{ obj.title }}</a></td>
                <td>{{obj.community.parent.parent}}</td>
            </tr>
            {% endfor %}
        </tbody>
    
    </table>
    
    <nav>
        <ul class="pager">
        {% if page_obj.has_previous %}
            <li><a href="?{% query_update request page=page_obj.previous_page_number %}">previous</a></li>
        {% endif %}
        <li>{{page_obj.number}} of {{paginator.num_pages}}</li>
        {% if page_obj.has_next %}
            <li><a href="?{% query_update request page=page_obj.next_page_number %}">next</a></li>
        {% endif %}
        </ul>
    </nav>
{% else %}
No rows
{%endif%}


[<a href="{%url 'registers:list_api' %}">API</a>]
{% endblock %}

pru/registers/templates/registers/register_map.html
{%extends 'registers/base.html' %}
{% load staticfiles %}
{% block css %}
    {{block.super}}
    <style>
    #map-canvas {
        width: 100%;
        height: 500px;
    }
    </style>
{% endblock %}
{% block javascript %}
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script src="{% static 'registers/map.js' %}"></script>
    <script type="text/javascript">
        init_map(document.getElementById("map-canvas"), "{% url 'registers:list_api' %}")
    </script>
    {{block.super}}
{% endblock %}
{% block main %}
    <div id="map-canvas"></div>
{% endblock %}